name: bmi_calculator

description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_picker: ^2.1.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  syncfusion_flutter_sliders: ^25.2.7

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
  fonts:
    - family: open-sans
      fonts:
        - asset: assets/fonts/open-sans.bold.ttf
        - asset: assets/fonts/open-sans.italic.ttf
        - asset: assets/fonts/open-sans.semibold.ttf
